name: Build and deploy Node.js app to Azure Web App - frontArsw

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.x

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Usar Node.js 18 LTS para mayor estabilidad
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Debug build output structure
        run: |
          echo "Build directory structure:"
          ls -la build
          ls -la build/* || echo "No subdirectories in build/"
          find build -type f | grep index.html || echo "No index.html found in build tree"

      - name: Create simplified server for SPA
        run: |
          # Crear un servidor express simplificado para SPA
          cat > server.js << 'EOL'
          const express = require('express');
          const compression = require('compression');
          const path = require('path');
          const fs = require('fs');

          const app = express();
          app.use(compression());

          // Health check for Azure
          app.get('/health', (req, res) => {
            res.status(200).send('OK');
          });

          // Log available paths
          console.log('Current directory:', __dirname);
          console.log('Files in directory:', fs.readdirSync(__dirname).join(', '));
          
          if (fs.existsSync(path.join(__dirname, 'public'))) {
            console.log('Public directory exists');
            console.log('Files in public:', fs.readdirSync(path.join(__dirname, 'public')).join(', '));
          }

          // Serve static files
          app.use(express.static('public'));

          // Serve index.html for all routes (SPA approach)
          app.get('*', (req, res) => {
            const indexPath = path.join(__dirname, 'public', 'index.html');
            
            if (fs.existsSync(indexPath)) {
              res.sendFile(indexPath);
            } else {
              res.status(404).send(`
                <html>
                  <head><title>Configuration Error</title></head>
                  <body>
                    <h1>Server Configuration Error</h1>
                    <p>index.html file not found at ${indexPath}</p>
                    <p>Current directory: ${__dirname}</p>
                    <p>Files available: ${fs.readdirSync(__dirname).join(', ')}</p>
                  </body>
                </html>
              `);
            }
          });

          const port = process.env.PORT || 8080;
          app.listen(port, () => {
            console.log(`Express server running on port ${port}`);
          });
          EOL

          # Crear web.config para IIS
          cat > web.config << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <webSocket enabled="false" />
              <handlers>
                <add name="iisnode" path="server.js" verb="*" modules="iisnode"/>
              </handlers>
              <rewrite>
                <rules>
                  <rule name="StaticContent">
                    <action type="Rewrite" url="public{REQUEST_URI}"/>
                  </rule>
                  <rule name="DynamicContent">
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
                    </conditions>
                    <action type="Rewrite" url="server.js"/>
                  </rule>
                </rules>
              </rewrite>
              <iisnode
                nodeProcessCommandLine="node"
                watchedFiles="web.config;*.js"
                loggingEnabled="true"
              />
            </system.webServer>
          </configuration>
          EOL

          # Crear .deployment
          cat > .deployment << 'EOL'
          [config]
          command = node server.js
          EOL

          # Package.json optimizado
          cat > deploy-package.json << 'EOL'
          {
            "name": "the-matrix-front",
            "version": "1.0.0",
            "engines": { "node": "18.x" },
            "dependencies": {
              "compression": "^1.7.4",
              "express": "^4.18.2"
            },
            "scripts": {
              "start": "node server.js"
            }
          }
          EOL

      - name: Create deployment package with correct structure
        run: |
          # Determinar la ubicaci칩n del index.html generado
          INDEX_HTML_PATH=$(find build -name "index.html" | head -1)
          
          if [ -z "$INDEX_HTML_PATH" ]; then
            echo "ERROR: No index.html found in the build directory!"
            exit 1
          fi
          
          # Obtener el directorio padre que contiene index.html
          STATIC_DIR=$(dirname "$INDEX_HTML_PATH")
          echo "Found index.html at $INDEX_HTML_PATH, will copy from $STATIC_DIR"
          
          # Crear estructura de despliegue
          mkdir -p deploy/public
          
          # Copiar archivos est치ticos al directorio public
          cp -r $STATIC_DIR/* deploy/public/ || true
          
          # Copiar servidor y configuraci칩n
          cp server.js deploy/
          cp web.config deploy/
          cp .deployment deploy/
          cp deploy-package.json deploy/package.json
          
          # Verificar estructura del despliegue
          echo "Deployment structure:"
          ls -la deploy
          echo "Public directory structure:"
          ls -la deploy/public || echo "No files in public directory!"
          
          # Instalar dependencias de producci칩n
          cd deploy && npm install --production

      - name: Zip artifact for deployment
        run: cd deploy && zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'frontArsw'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FRONTARSW }}